### PR TITLE
Dynamic sendbuffer

### PR DESCRIPTION
**Pull request by Wellidontcare**
This should make the sendbuffer dynamic, please check if there are no unforeseen bugs.

Related: #19

### CODE REVIEW

**Review by B-LechCode — COMMENTED** [review]
I wouldn't initialize the buffer in mainWorker::init - just use the dynamic resize option in mainWorker::run

**Comment by Wellidontcare** [comment]
The headerdata is written to the sendbuffer in the init function, so the memory has to be allocated.

**Comment by B-LechCode** [comment]
We could remove this, too. For me, ther is no good reason why we should allocate the buffer before knowing the real size demands.

**Comment by Wellidontcare** [comment]
This is true the extra allocation seems unnecessary, I updated the code accordingly please have a look.

**Review by B-LechCode — APPROVED** [review]
Perfect!

**Comment by B-LechCode** [comment]
Thank you :+1:

**Comment by B-LechCode** [comment]
Sorry, wrong button.

**Pull request merged**
